version: "3"
services:
  app:
    build:
      context: .
    volumes:
        - .:/app
    ports:
         - '3000:3000' 
    image: app:reactimage
    container_name: react_container
    command: npm start